### ISSUE TITLE
trying to compile it shows this

### ISSUE THREAD

**Issue by Bezizeja** [khuonghoanghuy/FNF-Pop-Engine-Rewrite#1]
source/states/playstate/PlayState.hx:29: characters 8-29 : Type not found : flixel.sound.FlxSound
source/states/playstate/PlayState.hx:58: characters 21-29 : Type not found : FlxSound
source/states/StoryMenuState.hx:22: lines 22-451 : ... Defined in this class
source/states/StoryMenuState.hx:330: characters 14-27 : Class<states.playstate.PlayState> has no field campaignScore
source/obj/Character.hx:130: characters 46-57 : Class<states.playstate.PlayState> has no field daPixelZoom
source/llua/Convert.hx:163: characters 15-26 : Type not found : LuaCallback
source/funkinLua/LuaCode.hx:63: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:65: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:74: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:76: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:85: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:87: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:96: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:98: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:101: characters 23-30 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:109: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:111: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:114: characters 23-30 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:122: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:122: characters 62-69 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:123: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:124: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:125: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:125: characters 59-66 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:128: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:128: characters 62-69 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:129: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:130: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:131: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:131: characters 59-66 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:134: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:134: characters 62-69 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:135: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:136: characters 31-38 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:136: characters 59-66 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:156: characters 48-55 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:158: characters 48-55 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:160: characters 23-30 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:213: characters 39-46 : Class<states.playstate.PlayState> has no field inClass
source/funkinLua/LuaCode.hx:214: characters 23-30 : Class<states.playstate.PlayState> has no field inClass
source/states/playstate/PlayCore.hx:48: characters 26-33 : Class<states.playstate.PlayState> has no field inClass
C:/haxelib/flixel-addons/3,1,1/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

- [x ] Windows

**Comment by MemeHovy** [comment]
use flixel 4.11.0 & flixel-addons 2.11.0
